<?php

namespace AppBundle\Repository;

/**
 * BlogPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogPostRepository extends \Doctrine\ORM\EntityRepository
{

    /*
     *
     public function getAllByTags(Array $tags) {

        return $this->getEntityManager()->
        createQuery('
              SELECT bp from AppBundle:BlogPost bp where 
              bp.blogTags like :tags
            ')->setParameter('tags', "%$tags[0]%")
            ->getResult();
    }
    */

}
